version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    volumes:
      - ./datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 4100:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 500M
